= Thomas and Friends

原版在 Uk 1984 开播，中文版在 2009 年开播。

== 介绍

在美丽的多多岛上，热心助人的托马斯是一辆可爱的火车头，他是一个完美主义者，最喜欢帮助别人，不过也常常因为过分热心而令自己卷入麻烦中。但是他乐观开朗，很快就会忘记不愉快的事，所以时常都是笑口常开、心情愉快。托马斯有很多的火车好朋友，他们团结友爱、互相帮助并且勤奋热情地工作，他们每天都会接载不同的乘客，因而发生了不少趣事，从中更认识到公平和友爱的重要。

== 适合年龄

3-6岁

== 资源

* YouTube
* CCTV
* 爱奇艺
* 腾讯视频

== 角色

[cols="1, 1, 2, 1, 4", format="csv", options="header"]
|===
Name, Number, Type, Country, First Apear
Belle, NWR 6120, steam-tank-coal, , Day of the Diesels
Ben (twin), SCC 2, steam-saddle tank-coal, England, Main Line Engines / Percy Takes the Plunge
Bill (twin), SCC 1, steam-saddle tank-coal, England, Main Line Engines / Percy Takes the Plunge
Daisy, NWR D1, diesel-mechanical-railcar, , Branch Line Engines / Daisy
Donald (twin), NWR 9 / BR 57646 / LMS 17646, steam-tender-coal, Scotland, The Twin Engines / Break Van
Douglas (twin), NWR 10 / BR 57647 / LMS 17647, steam-tender-coal, Scotland, The Twin Engines / Break Van
Diesel, , diesel-electric-shunter, , Duck and the Diesel Engine / Percy Takes the Plunge
Duck, NWR 8 / GWR/BR 5741, steam-pannier tank-coal, , Percy the Small Engine / Duck Takes Charge
Emily, NWR 12, steam-coal, England, Emily's New Coaches
Flynn, NWR, fire-petrol, US, Day of the Diesels
Gordon, NWR 4, steam-tender-coal, , The Three Railway Engines / Thomas and Gordon
Harold, , aircraft-helicopter-petrol, , Percy the Small Engine / Percy and Harold
Hiro, 51, steam-tender-coal, Japan, Specials-2009-Hero of the Rails
James, NWR 5, steam-tender-coal, , Thomas the Tank Engine / Thomas and Gordon
Kevin, , road-mobile crane-petrol, , Specials-2009-Hero of the Rails
Nia, EAR/NWR 18, steam-tank-coal, Kenya / England, Big World! Big Adventures!
Percy, NWR 6, steam-saddle tank-coal, , Troublesome Engines / Trouble in the Shed
Philip, NWR 68, diesel-electric-shunter, US, The Little Engine Who Raced Ahead
Rebecca, NWR 22, steam-coal, England, Confusion Without Delay
Rosie, NWR 37, steam-tank-coal, England / US, Thomas and the Birthday Mail
Samson, 15, steam-shddle tank-coal, England / Scotland, Marion and the Dinosaur
Salty, NWR 2991, diesel-electric-shunter, , Salty's Secret
Sidney, , diesel-electric-shunter, , Day of the Diesels
Stephen, L&MR 1, steam-tender-coal, , King of the Railway
Thomas, NWR 1 / LB&SCR 70, steam-tank-coal, England,
Toby, NWR 7 / BR 68221 / LNER 8221 / LNER 7127 / GER 127, steam-tram-coal, , Toby the Tram Engine / Toby and the Stout Gentleman
Victor, 1173, steam-saddle/pannier tank-oil, Cuba / US, Hero of the Rails
Yong Bao, , steam-tender-coal, China, The Great Race
Sir Topham Hatt, , Fat Controller, , The Three Railway Engines / Thomas and Gordon
|===

* BR = British Railways
* EAR = East African Railways
* GER = Great Eastern Railway
* L&MR = Liverpool and Manchester Railway
* LNER = London and North Eastern Railway
* NWR = North Western Railway
* SCC = Sodor China Clay Company

== 主题曲

----
They’re two, they’re four
两辆，四辆
They’re six, they’re eight
六辆和八辆
Shunting trucks and hauling freight
拉着货车厢，载着货物。
Red and green and brown and blue
红色、绿色、棕色和蓝色
They’re the Really Useful crew
他们是非常有用的小火车
All with different roles to play
他们扮演着不同的角色
Round Tidmouth sheds or far away
绕着提茅斯机房或是更远的地方
Down the hills and round the bends
开下山丘，绕过转弯
Thomas and his friends
托马斯和他的朋友们
Thomas,he’s the cheeky one
托马斯的胆子大
James is vain but lots of fun
詹姆斯爱炫耀但是他很有意思
Percy pulls the mail on time
培西准时去拉邮件
Gordon thunders down the line
高登轰隆隆的开过铁轨
Emily really knows her stuff
艾蜜莉，确实精通业务
Herry toots and huffs and puffs
亨利，鸣响汽笛，喷气再喷气
Edward wants to help and share
爱德华，想帮忙和分享
Toby,well let’s say-he’s square
托比我们这么说他吧，他很正直
They’re two, they’re four
两辆，四辆
Thry’re six, they’re eight
六辆和八辆
Shunting trucks and hauling freight
拉着货车厢，载着货物。
Red and green and brown and blue
红色、绿色、棕色和蓝色
They’re the Really Useful crew
他们是非常有用的小火车
All with different roles to play
他们扮演着不同的角色
Round Tidmouth sheds or far away
绕着提茅斯机房或是更远的地方
Down the hills and round the bends
开下山丘，绕过转弯
Thomas and his friends
托马斯和他的朋友们
----

== Ref

* https://ttte.fandom.com/wiki/
